export { default as About } from "./About"
export { default as Contact } from "./Contact"
export { default as Expertise } from "./Expertise"
export { default as Projects } from "./Projects"
export { default as Start } from "./Start"
